### ISSUE TITLE
Flexible remapper

### ISSUE THREAD

**Issue by OpheliaMiralles** [ecmwf/anemoi-models#82]
### Use of custom remappers for training.

Right now, only the angle to cosine/sine remapper is provided with anemoi-models. I feel like there might be a need for additional 1-to-1 remappers, e.g. mapping precipitation to log precipitation during training to facilitate the learning. I am currently adding 3 remappers of the sort

- log1p, mapping $x$ to $\log(1+x)$ and back using expm1 from torch;
- sqrt, mapping $x$ to $\sqrt{x}$ and back;
- boxcox, mapping $x$ to $(x^\{\lambda}-1) / \lambda \text{ if } \lambda \neq 0 \text{ else } \log(x)$ and back. 

Boxcox transforms are used to control the variable spread and generate Gaussian-like data. Coments are welcome regarding the need for such remappers by the community.

### Organisation

MeteoSwiss

**Comment by sahahner** [comment]
Hi Ophelia,
If I understand the issue correctly you want to convert a variable in place. 
I would recommend creating a new class of preprocessors called for example "converter". I wrote some code on that already, which should have been shared with you already. 
The remapper always clones the tensors and also changes the position of the variables since it is thought to do one-to-many remappings. This is why I would not recommend using the remapper for in-place conversion of variables.

**Comment by sahahner** [comment]
> Does it really change the performance to clone the tensor? Did you run some tests?

Yes, I tested this thoroughly and the performance is not slower. Also, memory consumption does not increase significantly. Feel free to write me an email and I can point you to the results.

Note that the remapper must be applied after the other preprocessors since it changes the order of variables.

**Comment by sahahner** [comment]
> want to apply the link function (I prefer this term) while conserving the original variable, e.g. give the network x and l o g ⁡ ( x ) as input for example? Then it would make sense to do that in the remapper

That does indeed sound like a nice application for the remapper! :) Note that the newly created variables cannot be normalized, as the normalizers always use the original ordering of the variables. (see comment above)

**Comment by OpheliaMiralles** [comment]
I tried to propose a version in #88 where the remapping occurs in place for 1-to-1 remapping, and the code is unchanged for more complex mappings, though the name has been changed into multimapper (module and object) to let the remapper be the 1-to-1 mapping. Maybe you could be a reviewer @sahahner ?

**Comment by sahahner** [comment]
Closed by https://github.com/ecmwf/anemoi-models/pull/88
